Ligen <- c("BL", "BPL", "SerA", "LaLi", "Lig1", "ED", "TurL")
#setwd("E:/Uni Arbeit/WM_Modellierungen/Projekt III/web scraping/Fitting")



source("Fitting Functions/Fitting Pois.R")
sapply(Ligen, exe.pois)

source("Fitting Functions/Fitting Pois Lasso.R")
exe.pois.lasso("BPL")
exe.pois.lasso("BL")
exe.pois.lasso("SerA") 
exe.pois.lasso("LaLi")
exe.pois.lasso("Lig1")
exe.pois.lasso("ED")
exe.pois.lasso("TurL")

source("Fitting Functions/Fitting Pois_both.R")
sapply(Ligen, exe.pois.both)

source("Fitting Functions/Fitting Pois Lasso_both.R")
exe.pois.lasso.both("BPL")
exe.pois.lasso.both("BL")
exe.pois.lasso.both("SerA")
exe.pois.lasso.both("LaLi")
exe.pois.lasso.both("Lig1")
exe.pois.lasso.both("ED")
exe.pois.lasso.both("TurL")

library(parallel)

## cop single
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting Cop.R"); exe.cop(Liga, Cop = "F")})
stopCluster(cl)
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting Cop.R"); exe.cop(Liga, Cop = "FGM")})
stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop.R"); exe.cop(Liga, Cop = "N")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop.R"); exe.cop(Liga, Cop = "C0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop.R"); exe.cop(Liga, Cop = "G0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop.R"); exe.cop(Liga, Cop = "J0")})
#stopCluster(cl)

## cop both
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "F")})
stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "N")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "C0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "G0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "J0")})
#stopCluster(cl)
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting Cop_both.R"); exe.cop.both(Liga, Cop = "FGM")})
stopCluster(cl)

## cop equal penalty
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "F")})
stopCluster(cl)
cl <- makeCluster(4)
parSapply(cl, Ligen[4:7], function(Liga) {source("Fitting Functions/Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "FGM")})
stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "N")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "C0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "G0")})
#stopCluster(cl)
#cl <- makeCluster(7)
#parSapply(cl, Ligen, function(Liga) {source("Fitting GJRM equal.R"); exe.cop.equal(Liga, Cop = "J0")})
#stopCluster(cl)

## cop equal penalty both.
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting GJRM equal both.R"); exe.cop.equal.both(Liga, "F")})
stopCluster(cl)
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting GJRM equal both.R"); exe.cop.equal.both(Liga, "FGM")})
stopCluster(cl)
#cl <- makeCluster(4)
#parSapply(cl, Ligen[1:4], function(Liga) {source("Fitting GJRM equal both.R"); exe.cop.equal.both(Liga, "C0")})
#stopCluster(cl)



## Warning: Each of these may take up to a few hours of time. Further parallelisation onto matchdays is possible
## and what I did for modelling all leagues together.

## cop lasso penalty
#source("Fitting GJRM lasso.R")
#exe.cop.lasso("BPL", "F", 2015)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("BPL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("BL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("SerA", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("LaLi", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("Lig1", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("ED", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("TurL", "F", s.year = year)})
stopCluster(cl)

## and FGM Copula:
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("BPL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("BL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("SerA", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("LaLi", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("Lig1", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("ED", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso.R"); exe.cop.lasso("TurL", "FGM", s.year = year)})
stopCluster(cl)

#### Cop lasso both
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("BPL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("BL", "F",  s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("LaLi", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("Lig1", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("SerA", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("ED", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("TurL", "F", s.year = year)})
stopCluster(cl)
## FGM
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("BPL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("BL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("SerA", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("LaLi", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("Lig1", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("ED", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso_both.R"); exe.cop.lasso.both("TurL", "FGM", s.year = year)})
stopCluster(cl)

## GJRM lasso + equal penalties
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("BPL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("BL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("Lig1", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("LaLi", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("SerA", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("ED", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("TurL", "F", s.year = year)})
stopCluster(cl)
### FGM
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("BPL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("BL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("Lig1", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("LaLi", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("SerA", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("ED", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal.R"); exe.cop.lasso.equal("TurL", "FGM", s.year = year)})
stopCluster(cl)

## Jetzt noch lasso+equal auf beide formulas (both). 
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("BPL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("BL", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("Lig1", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("LaLi", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("SerA", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("ED", "F", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("TurL", "F", s.year = year)})
stopCluster(cl)

cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("BPL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("BL", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("Lig1", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("LaLi", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("SerA", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("ED", "FGM", s.year = year)})
stopCluster(cl)
cl <- makeCluster(5)
parSapply(cl, 2015:2019, function(year){source("Fitting Functions/Fitting GJRM lasso+equal_both.R"); exe.cop.lasso.equal.both("TurL", "FGM", s.year = year)})
stopCluster(cl)




## RF 
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting RF.R"); exe.rf(Liga)})
stopCluster(cl)

cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting RF_both.R"); exe.rf.both(Liga)})
stopCluster(cl)

## ordinal:
cl <- makeCluster(7)
parSapply(cl, Ligen, function(Liga) {source("Fitting Functions/Fitting OrdinalReg.R"); exe.ordinal(Liga)})
stopCluster(cl)


## xgboost is already using multiple cores, so single calls here.
source("Fitting Functions/Fitting xgboost.R")
exe.xgboost("BPL")
exe.xgboost("BL")
exe.xgboost("SerA")
exe.xgboost("LaLi") 
exe.xgboost("Lig1") 
exe.xgboost("ED")
exe.xgboost("TurL")

source("Fitting xgboost_both.R")
exe.xgboost.both("BPL")
exe.xgboost.both("BL")
exe.xgboost.both("SerA")
exe.xgboost.both("LaLi")
exe.xgboost.both("Lig1")
exe.xgboost.both("ED")
exe.xgboost.both("TurL")

## add LASSO to poisson approaches.
